name: littlemiss
favicon: null
layout_spectrum: 0.8423282371368259
typography_spectrum: 0.026162852300330997
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.7805032993201166
  lightness: 0.4640144258737564
  saturation: 0.21615943452343345
  rhythmicContrast: 0.4204457844607532
purpose: []
